# Produce the chatbot graph
# display(Image(graph.get_graph().draw_mermaid_png()))

# Define a function to execute the chatbot, streaming each message
def stream_tool_response(user_input: str):
    for event in graph.stream({"messages": [("user", user_input)]}):
        
        # Return the agent's last response
        for value in event.values():
            print("Agent:", value["messages"])
            
# Define the query and run the chatbot
user_query = "US Congress"
stream_tool_response(user_query)


# Agent: [AIMessage(content='', additional_kwargs={'tool_calls': [{'index': 0, 'id': 'call_dOzJAxVgMfPWf20yWIrXh4Jj', 'function': {'arguments': '{"query":"US Congress"}', 'name': 'wikipedia'}, 'type': 'function'}]}, response_metadata={'finish_reason': 'tool_calls', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_560af6e559', 'service_tier': 'default'}, id='run--59b07dce-fdef-4be5-8605-b83bc808748f-0', tool_calls=[{'name': 'wikipedia', 'args': {'query': 'US Congress'}, 'id': 'call_dOzJAxVgMfPWf20yWIrXh4Jj', 'type': 'tool_call'}])]
#     Agent: [ToolMessage(content="Page: United States Congress\nSummary: The United States Congress is the legislative branch of the federal government of the United States. It is a bicameral legislature, including a lower body, the U.S. House of Representatives, and an upper body, the U.S. Senate. They both meet in the United States Capitol in Washington, D.C. \nMembers of Congress are chosen through direct election, though vacancies in the Senate may be filled by a governor's appointment. Congress has a total of 535 voting members, a figure which includes 100 senators and 435 representatives; the House of Representatives has 6 additional non-voting members. The vice president of the United States, as president of the Senate, has a vote in the Senate only when there is a tie.\nCongress convenes for a two-year term, commencing every other January. Elections are held every even-numbered year on Election Day. The members of the House of Representatives are elected for the two-year term of a Congress. The Reapportionment Act of 1929 established that there be 435 representatives, and the Uniform Congressional District Act requires that they be elected from single-member constituencies or districts. It is also required that the congressional districts be apportioned among states by population every ten years using the U.S. census results, provided that each state has at least one congressional representative. Each senator is elected at-large in their state for a six-year term, with terms staggered, so every two years approximately one-third of the Senate is up for election. Each state, regardless of population or size, has two senators, so currently, there are 100 senators for the 50 states.\nArticle One of the U.S. Constitution requires that members of Congress be at least 25 years old for the House and at least 30 years old for the U.S. Senate, be a U.S. citizen for seven years for the House and nine years for the Senate, and be an inhabitant of the state which they represent. Members in both chambers may stand for re-election an unlimited number of times.\nCongress was created by the U.S. Constitution and first met in 1789, replacing the Congress of the Confederation in its legislative function. Although not legally mandated, in practice members of Congress since the late 19th century are typically affiliated with one of the two major parties, the Democratic Party or the Republican Party, and only rarely with a third party or independents affiliated with no party. Members can also switch parties at any time, though this is uncommon.", name='wikipedia', id='a1e21fb8-42aa-417a-82a5-8be98e4fa5cc', tool_call_id='call_dOzJAxVgMfPWf20yWIrXh4Jj')]
#     Agent: [AIMessage(content="The United States Congress is the legislative branch of the federal government of the United States, consisting of two chambers: the U.S. House of Representatives and the U.S. Senate. Both chambers meet at the United States Capitol in Washington, D.C.\n\n### Key Points about the U.S. Congress:\n\n- **Composition**: Congress has a total of 535 voting members: 100 senators (two from each state) and 435 representatives. Additionally, the House of Representatives includes 6 non-voting members.\n- **Election and Terms**:\n  - Members of the House are elected for two-year terms.\n  - Senators serve six-year terms, with elections staggered so that approximately one-third of the Senate is up for election every two years.\n- **Age and Citizenship Requirements**:\n  - House members must be at least 25 years old and U.S. citizens for at least seven years.\n  - Senators must be at least 30 years old and citizens for at least nine years.\n- **Vacancies**: Senate vacancies may be filled by a governor's appointment.\n- **Session Duration**: Congress convenes for a two-year term, beginning every other January, with elections held in even-numbered years.\n- **Political Affiliation**: Although 

# Import the modules for saving memory
from langgraph.checkpoint.memory import MemorySaver

# Modify the graph with memory checkpointing
memory = MemorySaver()

# Compile the graph passing in memory
graph = graph_builder.compile(checkpointer=memory)


def stream_memory_responses(user_input: str):
    config = {"configurable": {"thread_id": "single_session_memory"}}
    
    # Stream the events in the graph
    for event in graph.stream({"messages": [("user", user_input)]}, config):
        
        # Return the agent's last response
        for value in event.values():
            if "messages" in value and value["messages"]:
                print("Agent:", value["messages"])

stream_memory_responses("Tell me about the Eiffel Tower.")
stream_memory_responses("Who built it?")

# <script.py> output:
#     Agent: [AIMessage(content='', additional_kwargs={'tool_calls': [{'index': 0, 'id': 'call_uy7LFRNwBqcFsI7aBlRac2xB', 'function': {'arguments': '{"query":"Eiffel Tower"}', 'name': 'wikipedia'}, 'type': 'function'}]}, response_metadata={'finish_reason': 'tool_calls', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_560af6e559', 'service_tier': 'default'}, id='run--1e3db09c-6156-433e-9ac7-5dcad1f0528c-0', tool_calls=[{'name': 'wikipedia', 'args': {'query': 'Eiffel Tower'}, 'id': 'call_uy7LFRNwBqcFsI7aBlRac2xB', 'type': 'tool_call'}])]
#     Agent: [ToolMessage(content='Page: Eiffel Tower\nSummary: The Eiffel Tower (  EYE-fəl; French: Tour Eiffel [tuʁ ɛfɛl] ) is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower from 1887 to 1889.\nLocally nicknamed "La dame de fer" (French for "Iron Lady"), it was constructed as the centrepiece of the 1889 World\'s Fair, and to crown the centennial anniversary of the French Revolution. Although initially criticised by some of France\'s leading artists and intellectuals for its design, it has since become a global cultural icon of France and one of the most recognisable structures in the world. The tower received 5,889,000 visitors in 2022. The Eiffel Tower is the most visited monument with an entrance fee in the world: 6.91 million people ascended it in 2015. It was designated a monument historique in 1964, and was named part of a UNESCO World Heritage Site ("Paris, Banks of the Seine") in 1991.\nThe tower is 330 metres (1,083 ft) tall, about the same height as an 81-storey building, and the tallest structure in Paris. Its base is square, measuring 125 metres (410 ft) on each side. During its construction, the Eiffel Tower surpassed the Washington Monument to become by far the tallest human-made structure in the world, a title it held for 41 years until the Chrysler Building in New York City was finished in 1930. It was the first structure in the world to surpass both the 200 meters and 300 meters mark in height. Due to the addition of a broadcasting aerial at the top of the tower in 1957, it is now taller than the Chrysler Building by 5.2 metres (17 ft). Excluding transmitters, the Eiffel Tower is the second tallest free-standing structure in France after the Millau Viaduct.\nThe tower has three levels for visitors, with restaurants on the first and second levels. The top level\'s upper platform is 276 m (906 ft) above the ground—the highest public observation deck in the European Union. Tickets can be purchased to ascend by stairs or lift to the first and second levels. The climb from ground level to the first level is over 300 steps, as is the climb from the first level to the second, making the entire ascent a 600-step climb. Although there is a staircase to the top level, it is usually accessible only by lift. On this top, third level, is a private apartment built for Gustave Eiffel, who decorated it with furniture made by Jean Lachaise and invited friends such as Thomas Edison.', name='wikipedia', id='96726b4a-ed35-4fb5-a875-b8c01e111204', tool_call_id='call_uy7LFRNwBqcFsI7aBlRac2xB')]
#     Agent: [AIMessage(content="The Eiffel Tower (French: Tour Eiffel) is a wrought-iron lattice tower located on the Champ de Mars in Paris, France. Named after the engineer Gustave Eiffel, whose company designed and built the tower between 1887 and 1889, it was constructed as the centerpiece for the 1889 World's Fair to commemorate the centennial anniversary of the French Revolution.\n\nInitially criticized by some of France's leading artists and intellectuals, the Eiffel Tower has since transformed into a global cultural icon and one of the most recognizable structures in the world. In 2022, it attracted 5,889,000 visitors, making it the most visited monument in the world with an entrance fee. It was designated a monument historique in 1964 and became part of a UNESCO World Heritage Site in 1991.\n\nThe tower stands at 330 meters (1,083 feet) tall, roughly the height of an 81-story building, and is the tallest structure in Paris. Its base is square, measuring 125 meters (410 feet) on each side. During its construction, it became the tallest man-made structure in the world, a record it held for 41 years until surpassed by the Chrysler Building in New York City in 1930. The Eiffel Tower was also the first structure to exceed 200 meters and 300 meters in height. Following the addition of a broadcasting aerial in 1957, it is now taller than the Chrysler Building by 5.2 meters (17 feet).\n\nVisitors to the Eiffel Tower can access three levels, with restaurants on the first and second levels. The upper platform of the top level is 276 meters (906 feet) above the ground, serving as the highest public observation deck in the European Union. Tickets can be purchased to ascend by stairs or lift to the first two levels, although the climb to the top level is typically only accessible by lift. A private apartment on the top level was originally built for Gustave Eiffel, featuring furniture made by Jean Lachaise and hosting guests like Thomas Edison.", additional_kwargs={}, response_metadata={'finish_reason': 'stop', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_560af6e559', 'service_tier': 'default'}, id='run--13f2e294-5e27-4180-be0e-e64ede02b2da-0')]
#     Agent: [AIMessage(content='', additional_kwargs={'tool_calls': [{'index': 0, 'id': 'call_cuxczULJMeuwm5cCwfoF7Q4R', 'function': {'arguments': '{"query":"Gustave Eiffel"}', 'name': 'wikipedia'}, 'type': 'function'}]}, response_metadata={'finish_reason': 'tool_calls', 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_560af6e559', 'service_tier': 'default'}, id='run--5cc35c48-31b4-4ee3-a87f-94056505fd75-0', tool_calls=[{'name': 'wikipedia', 'args': {'query': 'Gustave Eiffel'}, 'id': 'call_cuxczULJMeuwm5cCwfoF7Q4R', 'type': 'tool_call'}])]
#     Agent: [ToolMessage(content='Page: Gustave Eiffel\nSummary: Alexandre Gustave Eiffel (  EYE-fəl, French: [alɛksɑ̃dʁ ɡystav ɛfɛl]; né Bonickhausen dit Eiffel; 15 December 1832 – 27 December 1923) was a French civil engineer. A graduate of École Centrale des Arts et Manufactures, he made his name with various bridges for the French railway network, most famously the Garabit Viaduct. He is best known for the world-famous Eiffel Tower, designed by his company and built for the 1889 Universal Exposition in Paris, and his contribution to building the Statue of Liberty in New York. After his retirement from engineering, Eiffel focused on research into meteorology and aerodynamics, making significant contributions in both fields.', name='wikipedia', id='3d95dc61-1723-47c3-9cb6-a519aa722ec0', tool_call_id='call_cuxczULJMeuwm5cCwfoF7Q4R')]
#     Agent: [AIMessage(content='The Eiffel Tower was built by Alexandre Gustave Eiffel, a French civil engineer. Born on December 15, 1832, Eiffel graduated from the École 


